function [ N ] = NormalDistribution( count )
%NORMALDISTRIBUTION generates two random number in standard normal
%distribution, which are not correlative.
%   N1 and N2 generated by Box-Muller method
%   if count = 1,N is 1*1,
%   if count = 2,N is 1*2,
%   count default is 1.

if count ~= 1 && count ~= 2
    count = 1;
end

U1 = rand;
U2 = rand;
switch count
    case 1
        N =  sqrt( -2 * log(U1) ) * cos( 2 * pi * U2 );
    case 2
        temp1 = sqrt( -2 * log(U1) );
        temp2 = 2 * pi * U2;
        N(1,1) = temp1 * cos( temp2 );
        N(1,2) = temp1 * sin( temp2 );
end

end

